# Generated by Django 3.1 on 2022-12-23 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_job_post_id_alter_resume_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('school_name', models.CharField(max_length=50)),
                ('school_head', models.CharField(default='', max_length=50)),
                ('school_code', models.CharField(max_length=8)),
                ('classes', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('pin', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('authorized_by', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
