# Generated by Django 3.1 on 2022-12-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221223_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
