# Generated by Django 3.1 on 2022-12-23 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profileavatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='File', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv'])])),
            ],
        ),
    ]
