# Generated by Django 3.1 on 2022-12-23 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profileavatarfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv'])]),
        ),
    ]
