# Generated by Django 3.1 on 2022-12-27 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221223_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatarfile',
            name='avatar',
            field=models.FileField(upload_to='File', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
    ]
