# Generated by Django 3.1 on 2022-12-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221227_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileAvatar',
        ),
        migrations.DeleteModel(
            name='ProfileAvatarFile',
        ),
    ]
