# Generated by Django 3.1 on 2022-12-27 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221227_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
