# Generated by Django 3.1 on 2022-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221227_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='package',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
