# Generated by Django 3.1 on 2023-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20221228_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='ip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
