# Generated by Django 3.1 on 2023-01-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_job_post_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='ip',
        ),
    ]
